### ISSUE TITLE
Seminar 5 Bug Fix

### ISSUE THREAD

**Issue by lijiarui** [wechaty/bot5#235]
- [ ] Add author profile to author.yml
- [x] change Youtube video title and description, eg: https://www.youtube.com/watch?v=yR9_-CpUEIM&list=PL8hd9KDTdarDJdNcARh5nInSkurE2wDXu
- [x] Choose a suitable cover for the video
- [x] 'BOT5.Club - Conversational User Interface-咨询场景中下一代AI人机交互-基于 Authing 识别 Wechaty 中的微信用户可行性 2020#05(全)' --> '2021#05'. It's year 2021!

**Comment by scy1207-git** [comment]
Fixed on video desc
