### ISSUE TITLE
Utterance bot cannot work as expect

### ISSUE THREAD

**Issue by lijiarui** [wechaty/bot5#245]
Our utterance bot cannot file issues automatically since the fifth bot5 event.

![image](https://user-images.githubusercontent.com/6419514/139585768-ef152a1b-c5ab-45e1-a806-47eedbf13ad8.png)

**Comment by huan** [comment]
The Utterance bot will not create issues by itself. 

There must have been someone leaving a comment under the blog post so that the bot can post the comment here as a new issue.

**Comment by lijiarui** [comment]
Got it
